SRCS = main.cpp			\
		HumanA.cpp		\
		HumanB.cpp		\
		Weapon.cpp		\

NAME = weapons

PARAMS = 

FLAGS = -Wall -Wextra -Werror -std=c++98

all : compile run

compile :
	@g++ $(FLAGS) $(SRCS) -o $(NAME)

run :
	@./$(NAME) $(PARAMS)